In [ ]:
# 1 
import numpy as np

# 2
zeros = np.zeros(10)
zeros

In [ ]:
# 3
ones = np.ones(10)
ones

In [14]:
# 4
fives = np.ones(10) * 5
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
# 5
print(np.arange(10,51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
# 6 the first number is the number of ints, second is the range it goes up to, third is that it's even
print(np.arange(10,51,2))

In [16]:
# 7 Create an array of even integers from 10-50
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
# 8 Use NumPy to generate a random number between 0-1
print(np.random.rand(1))


[0.66026983]


In [24]:
# 9 Create a matrix using the following statements and display it:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
#10 

# a
mat.sum()

# b
mat.std()

# c
mat1 = np.ones(25).reshape(5,5)
mat1

#d 
mat1 + mat

#e 
mat * mat1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])